apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: juice-shop
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.securecodebox.io/'
    targetRevision: 3.14.3
    chart: juice-shop
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true