apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd  
spec:
  project: default
  source:
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.2.0
    chart: ingress-nginx
    helm:
      values: |
        controller:
          podAnnotations:
            prometheus.io/scrape: "true"
            prometheus.io/port: "10254"
          metrics:
            enabled: true
            serviceMonitor:
              additionalLabels:
                release: prometheus
              enabled: true        
            service:
              annotations:
                prometheus.io/port: "10254"
                prometheus.io/scrape: "true"            
          extra_args:
            enable-ssl-passthrough: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
    automated:
      selfHeal: true
      prune: true